### ISSUE TITLE
Cannot save user profile setting for "I don't want to be notified of changes that I make myself"

### ISSUE THREAD

**Issue by arnisjuraga** [guilhermenoronha/redmine_send_mails#4]
After installation, you cannot save settings for user.

Plugin setting for "Always check the checkbox for send e-mail" works great, but "I don't want to be notified of changes that I make myself" stays unchecked no matter what.

![image](https://f.cloud.github.com/assets/2185289/1459869/5b45f5a6-43fe-11e3-8313-9393ac61ecad.png)

System version: https://github.com/guilhermenoronha/redmine_send_mails/issues/1#issuecomment-27347967

**Comment by arnisjuraga** [comment]
I can confirm - that with these settings: 

``` Environment:
  Redmine version                2.3.3.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [i486-linux]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               Mysql2
Redmine plugins:
  add_link                       0.0.1
  clipboard_image_paste          1.8
  progressive_projects_list      0.0.2
  redmine_ckeditor               0.2.1
  redmine_github_hook            0.2.0
  redmine_issue_checklist        2.0.5
  redmine_lightbox               0.0.1
  redmine_send_mails             0.2.23x
```

everyting works - I can save preferences correctly. I hope this is not connected with my old system settings:

**Comment by guilhermenoronha** [comment]
Fixed, please check!

**Comment by arnisjuraga** [comment]
Works with:

```
Redmine version                2.3.3.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [i486-linux]
  Rails version                  3.2.13
```
