### ISSUE TITLE
"label" for profile settings checkbox - mouse click on/off does not work

### ISSUE THREAD

**Issue by arnisjuraga** [guilhermenoronha/redmine_send_mails#5]
label must have the same name, as checkbox input ID, so - the mouse click on the label text will check/unckeck setting.

![image](https://f.cloud.github.com/assets/2185289/1464621/2db657c0-454d-11e3-9ebe-bc9ac401fe17.png)

**Comment by guilhermenoronha** [comment]
Fixed, please check!

**Comment by arnisjuraga** [comment]
Now everything is even worse... :)
- without plugin - label is working correctly:
  ![image](https://f.cloud.github.com/assets/2185289/1487390/15ccdf0c-4733-11e3-9e34-b445fb526805.png)
- with plugin - both labels "for" attribute differs from input "id" attribute:
  ![image](https://f.cloud.github.com/assets/2185289/1487399/4befbfd2-4733-11e3-945c-b6ad166931c4.png)
  :

**Comment by guilhermenoronha** [comment]
I'm sorry but I didn't realize your problem. Has it some restriction to you use the plugin? If you can explain to me details of it... Thanks.

**Comment by arnisjuraga** [comment]
the problem is: after plugin installation, in user profile page you can set 2 checkboxes.

But - the "label" tag for these checkboxes ar incorrect. Usually - if you have "label" tag for checkbox input field - you can check/uncheck it by mouse click ON THE LABEL TEXT (see this print screen): ![image](https://f.cloud.github.com/assets/2185289/1490220/b361e7f8-478d-11e3-8913-9876be3b2697.png)

If the label is set incorrectly, then mouse click on the text does not work. 

In previous print screen I show HTML source, where you can see, that ID and label FOR attributes are different. So - clicking on label text does not check/unckeck input checkboxes.

**Comment by guilhermenoronha** [comment]
Fixed. Once more thanks for feedback! If it don't fix your problem, please re-open the issue.

**Comment by arnisjuraga** [comment]
OK, I confirm that with: 

```
git clone -b master https://github.com/guilhermenoronha/redmine_send_mails.git redmine_send_mails
```

now works! 
It seems, I have been cloning 2.3.x branch before?

**Comment by guilhermenoronha** [comment]
Yeah, I've merged the branch into the master. I'm not intending to use the branch 2.3.x for awhile.
